---
- name: HarborPlaybook
  hosts: harborhosts
  become: true
  remote_user: root
  gather_facts: true
  vars_files:
    - ./vars/main.yml
  roles:
    - role: add_users
    - role: sysctl
    - role: docker
    - role: harbor
  environment: "{{ proxy_env }}"
