---
- name: Get the users home directory
  shell: >
    egrep "^{{ harbor_user }}:" /etc/passwd | awk -F: '{ print $6 }'
  changed_when: false
  register: user_home

- name: Creates harbor directory
  file:
    state: directory
    owner: "{{ harbor_user }}"
    mode: 0700
    dest: "{{ user_home.stdout }}/"

- name: Download harbor install from Github
  unarchive:
    src: "{{ harbor_install_download_url }}"
    dest: "{{ user_home.stdout }}"
    mode: 0777
    remote_src: yes
  changed_when: false

- name: Copy config.cfg
  template:
    src: 'harbor.yml.j2'
    dest: "{{ user_home.stdout }}/harbor/harbor.yml"
    owner: "{{ harbor_user }}"
    group: "{{ harbor_user }}"
    mode: '0755'
  ignore_errors: true
  
- name: Copy ssl cert to user home directory
  copy:
    src: "{{ harbor_ssl_cert }}"
    dest: "{{ user_home.stdout }}/harbor/{{ harbor_ssl_cert }}"
    owner: "{{ harbor_user }}"
    mode: 0755
  ignore_errors: true

- name: Copy ssl key to user home directory
  copy:
    src: "{{ harbor_ssl_key }}"
    dest: "{{ user_home.stdout }}/harbor/{{ harbor_ssl_key }}"
    owner: "{{ harbor_user }}"
    mode: 0755
  ignore_errors: true

- name: "RUN install.sh"
  shell: 
    cmd: "./install.sh --with-chartmuseum"
    chdir: "{{ user_home.stdout }}/harbor/"
  changed_when: false

- name: Configure LDAP
  uri:
    url: https://{{ harbor_hostname }}:{{ harbor_https_port }}/api/v2.0/configurations
    method: PUT
    url_username: admin
    url_password: "{{ harbor_admin_password }}"
    body_format: json
    force_basic_auth: yes
    headers:
      Content-Type: "application/json"
    body:
      auth_mode: "ldap_auth"
      ldap_url: "{{ harbor_ldap_url }}"
      ldap_base_dn: "{{ harbor_ldap_base_dn}}"
      ldap_search_dn: "{{ harbor_ldap_search_dn }}"
      ldap_search_password: "{{ harbor_ldap_search_password }}"
      ldap_filter: "{{ harbor_ldap_filter }}"
      ldap_scope: "{{harbor_ldap_scope}}"
      ldap_timeout: "{{ harbor_ldap_timeout }}"
      ldap_uid: "{{ harbor_ldap_uid }}"
      self_registration: "{{ harbor_self_registration }}"
      #ldap_verify_cert: "{{ harbor_ldap_verify_cert }}"
      #ldap_group_admin_dn: "{{ harbor_ldap_group_admin_dn }}"
      #ldap_group_attribute_name: "{{ harbor_ldap_group_attribute_name }}"
      #ldap_group_base_dn: "{{ harbor_ldap_group_base_dn }}"
      #ldap_group_search_filter: "{{ harbor_ldap_group_search_filter }}"
      #ldap_group_search_scope: "{{ harbor_group_search_scope }}"
      #ldap_group_membership_attribute: "{{ harbor_group_membership_attribute }}"
    validate_certs: no
  when: harbor_ldap == True
